import { Link } from "react-router-dom";
import SEO from "@/components/SEO";
import { Zap, ArrowLeft, FileText } from "lucide-react";

const Section = ({ title, children }) => (
  <div className="mb-10">
    <h2 className="font-heading font-bold text-xl md:text-2xl text-white uppercase tracking-tight mb-4">{title}</h2>
    <div className="text-zinc-400 text-sm md:text-base leading-relaxed space-y-3">{children}</div>
  </div>
);

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950">
      <SEO title="Terms & Conditions | Formanti" url="https://www.formanti.com/terms" />
      {/* Header */}
      <div className="border-b border-zinc-800/50">
        <div className="container mx-auto px-4 max-w-4xl py-6 flex items-center gap-4">
          <Link to="/" className="flex items-center gap-2 text-zinc-400 hover:text-lime-400 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            <Zap className="w-5 h-5 text-lime-400" />
            <span className="font-heading font-bold text-lg uppercase tracking-tight text-white">Formanti</span>
          </Link>
        </div>
      </div>

      {/* Content */}
      <div className="container mx-auto px-4 max-w-4xl py-12 md:py-16">
        <div className="flex items-center gap-3 mb-2">
          <FileText className="w-8 h-8 text-lime-400" />
          <h1 className="font-heading font-black text-3xl md:text-4xl text-white uppercase tracking-tighter">Terms &amp; Conditions</h1>
        </div>
        <p className="text-zinc-500 text-sm mb-12">Last updated: July 7, 2026</p>

        <Section title="1. Acceptance of Terms">
          <p>
            These Terms &amp; Conditions ("Terms") govern your access to and use of Formanti ("Formanti", "we", "our", "us"), an AI-powered sports coaching platform available at formanti.com and its associated mobile application. Formanti is operated by <strong className="text-white">Harshit Mundra</strong>, an individual / sole proprietor based in Bengaluru, Karnataka, India. By creating an account, purchasing tokens, or otherwise using the service, you agree to be bound by these Terms. If you do not agree, please do not use the service.
          </p>
        </Section>

        <Section title="2. The Service">
          <p>
            Formanti provides AI-generated analysis of user-submitted sports videos, along with technique feedback, drills, training suggestions, equipment recommendations, and progress tracking across sports including badminton, tennis, table tennis, pickleball, cricket, swimming, football, and basketball.
          </p>
          <p>
            The analysis and feedback are generated by automated AI systems and are provided for informational and training-guidance purposes only. They are <strong className="text-white">not a substitute for professional coaching, medical, physiotherapy, or fitness advice</strong>. Always consult a qualified professional before beginning or modifying any training or exercise programme.
          </p>
        </Section>

        <Section title="3. Eligibility &amp; Accounts">
          <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to provide accurate information and to keep it up to date. If you are under 18, you must use the service with the involvement of a parent or guardian.</p>
        </Section>

        <Section title="4. Tokens, Pricing &amp; Payments">
          <p><strong className="text-white">Tokens</strong> are the in-app credits used to run AI analyses and access certain paid features. Tokens can be purchased in packs, with prices displayed in Indian Rupees (INR) inclusive of applicable taxes at checkout.</p>
          <p>Payments are processed by our third-party payment partner, <strong className="text-white">Razorpay</strong>. We do not store your card, UPI, or bank details on our servers. By making a purchase you also agree to Razorpay's terms.</p>
          <p>Tokens are credited to your account after successful payment confirmation. Tokens are non-transferable, hold no cash value, and are governed by our <Link to="/refund" className="text-lime-400 hover:text-lime-300">Refund Policy</Link> and <Link to="/cancellation" className="text-lime-400 hover:text-lime-300">Cancellation Policy</Link>.</p>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>Upload content you do not have the right to submit, or that infringes any third party's rights</li>
            <li>Upload unlawful, obscene, or harmful content, or content depicting individuals without their consent</li>
            <li>Attempt to reverse-engineer, disrupt, overload, or gain unauthorised access to the service</li>
            <li>Resell, redistribute, or commercially exploit the service or its outputs without our written permission</li>
          </ul>
        </Section>

        <Section title="6. User Content">
          <p>
            You retain ownership of the videos and content you submit. You grant us a limited licence to process your content solely to provide and improve the service (for example, to run the AI analysis and store your results). Please review our <Link to="/privacy" className="text-lime-400 hover:text-lime-300">Privacy Policy</Link> for details on how your data is handled.
          </p>
        </Section>

        <Section title="7. Intellectual Property">
          <p>
            All software, models, text, graphics, and branding that make up the Formanti platform are owned by Formanti or its licensors and are protected by applicable intellectual-property laws. The analysis output generated for your own videos is provided for your personal use.
          </p>
        </Section>

        <Section title="8. Disclaimers">
          <p>
            The service is provided on an "as is" and "as available" basis without warranties of any kind. AI-generated feedback may be incomplete or inaccurate. We do not guarantee any particular result, improvement, or outcome from using the service. You use the service and act on its feedback at your own risk.
          </p>
        </Section>

        <Section title="9. Limitation of Liability">
          <p>
            To the maximum extent permitted by law, Formanti shall not be liable for any indirect, incidental, or consequential damages, or for any loss arising from your use of, or inability to use, the service. Our total liability for any claim shall not exceed the amount you paid to us in the three months preceding the event giving rise to the claim.
          </p>
        </Section>

        <Section title="10. Termination">
          <p>
            We may suspend or terminate your access if you breach these Terms or misuse the service. You may stop using the service and request account deletion at any time (see our Cancellation Policy).
          </p>
        </Section>

        <Section title="11. Governing Law">
          <p>
            These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts at <strong className="text-white">Bengaluru, Karnataka</strong>.
          </p>
        </Section>

        <Section title="12. Changes to These Terms">
          <p>
            We may update these Terms from time to time. Material changes will be notified through the app or website. Continued use after changes take effect constitutes acceptance of the updated Terms.
          </p>
        </Section>

        <Section title="13. Contact">
          <p>For any questions about these Terms, contact us at:</p>
          <p>
            <a href="mailto:support@formanti.com" className="text-lime-400 hover:text-lime-300 transition-colors font-medium">support@formanti.com</a>
          </p>
          <p className="text-zinc-500 text-sm">
            Operated by: <strong className="text-white">Harshit Mundra</strong> (individual / sole proprietor)<br />
            Address: <strong className="text-white">__FULL_ADDRESS__</strong><br />
            Phone: <strong className="text-white">__PHONE__</strong>
          </p>
        </Section>

        {/* Back link */}
        <div className="pt-8 border-t border-zinc-800/50">
          <Link to="/" className="inline-flex items-center gap-2 text-zinc-500 hover:text-lime-400 transition-colors text-sm">
            <ArrowLeft className="w-4 h-4" /> Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
